# Generated by Django 5.2.6 on 2025-09-12 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-data_assinatura']},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_vencimento_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='tempo_video',
            field=models.DurationField(default=10),
        ),
    ]
