# Generated by Django 5.2.6 on 2025-09-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documentocontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='data_subiu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
