# Generated by Django 5.2.6 on 2025-09-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contrato_options_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_total',
        ),
    ]
