# Generated by Django 5.2.6 on 2025-09-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contrato_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.contrato'),
        ),
    ]
