# Generated by Django 5.2.6 on 2025-09-16 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_registro_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
