# Generated by Django 5.2.6 on 2025-11-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_registro_data_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='statuscontrato',
            options={'verbose_name': 'Status do Contrato', 'verbose_name_plural': 'Status dos Contratos'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
    ]
