# Generated by Django 5.2.6 on 2026-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_formapagamento_options_alter_local_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='link_cobranca',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Cobrança'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='link_notas',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Notas'),
        ),
    ]
