# Generated by Django 5.2.6 on 2026-08-13 11:31

import django.db.models.deletion
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import migrations, models


def criar_parcelas_existentes(apps, schema_editor):
    """Gera as parcelas dos contratos já cadastrados e migra os pagamentos
    antigos (primeiro_pagamento -> parcela 1, segundo_pagamento -> parcela 2)."""
    Contrato = apps.get_model("core", "Contrato")
    Parcela = apps.get_model("core", "Parcela")

    novas = []
    for contrato in Contrato.objects.all():
        inicio = contrato.data_vencimento_primeira_parcela or contrato.data_assinatura
        if not inicio:
            continue
        quantidade = contrato.vigencia_meses or 12
        pagamentos = {1: contrato.primeiro_pagamento, 2: contrato.segundo_pagamento}
        for i in range(quantidade):
            novas.append(Parcela(
                contrato=contrato,
                ciclo=1,
                numero=i + 1,
                vencimento=inicio + relativedelta(months=i),
                pago_em=pagamentos.get(i + 1),
            ))
    Parcela.objects.bulk_create(novas)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contrato_link_cobranca_contrato_link_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo', models.PositiveSmallIntegerField(default=1)),
                ('numero', models.PositiveSmallIntegerField()),
                ('vencimento', models.DateField()),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parcelas',
                'ordering': ['ciclo', 'numero'],
                'unique_together': {('contrato', 'ciclo', 'numero')},
            },
        ),
        migrations.RunPython(criar_parcelas_existentes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contrato',
            name='primeiro_pagamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='segundo_pagamento',
        ),
    ]
